# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bucket.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bucket.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0c\x62ucket.proto\"\'\n\x12InformationRequest\x12\x11\n\tbucket_id\x18\x01 \x01(\t\"P\n\x13InformationResponse\x12\x11\n\tbucket_id\x18\x01 \x01(\t\x12\x13\n\x0b\x62ucket_name\x18\x02 \x01(\t\x12\x11\n\tuser_name\x18\x03 \x01(\t2G\n\x06\x42ucket\x12=\n\x0eGetInformation\x12\x13.InformationRequest\x1a\x14.InformationResponse\"\x00\x62\x06proto3'
)




_INFORMATIONREQUEST = _descriptor.Descriptor(
  name='InformationRequest',
  full_name='InformationRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bucket_id', full_name='InformationRequest.bucket_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=55,
)


_INFORMATIONRESPONSE = _descriptor.Descriptor(
  name='InformationResponse',
  full_name='InformationResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bucket_id', full_name='InformationResponse.bucket_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bucket_name', full_name='InformationResponse.bucket_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='user_name', full_name='InformationResponse.user_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=57,
  serialized_end=137,
)

DESCRIPTOR.message_types_by_name['InformationRequest'] = _INFORMATIONREQUEST
DESCRIPTOR.message_types_by_name['InformationResponse'] = _INFORMATIONRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InformationRequest = _reflection.GeneratedProtocolMessageType('InformationRequest', (_message.Message,), {
  'DESCRIPTOR' : _INFORMATIONREQUEST,
  '__module__' : 'bucket_pb2'
  # @@protoc_insertion_point(class_scope:InformationRequest)
  })
_sym_db.RegisterMessage(InformationRequest)

InformationResponse = _reflection.GeneratedProtocolMessageType('InformationResponse', (_message.Message,), {
  'DESCRIPTOR' : _INFORMATIONRESPONSE,
  '__module__' : 'bucket_pb2'
  # @@protoc_insertion_point(class_scope:InformationResponse)
  })
_sym_db.RegisterMessage(InformationResponse)



_BUCKET = _descriptor.ServiceDescriptor(
  name='Bucket',
  full_name='Bucket',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=139,
  serialized_end=210,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetInformation',
    full_name='Bucket.GetInformation',
    index=0,
    containing_service=None,
    input_type=_INFORMATIONREQUEST,
    output_type=_INFORMATIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BUCKET)

DESCRIPTOR.services_by_name['Bucket'] = _BUCKET

# @@protoc_insertion_point(module_scope)
